In [1]:
import torch

In [2]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [3]:
a

tensor([5.], requires_grad=True)

In [4]:
b

tensor([6.], requires_grad=True)

In [5]:
y = a**3 - b**2

In [6]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [7]:
#dy/da = 3a**2 = 75
#dy/db = -2b = -12

In [10]:
print(a.grad)
#print(b.grad) --->None

None


In [11]:
y.backward()

In [12]:
a.grad

tensor([75.])

In [13]:
b.grad

tensor([-12.])

In [43]:
#define weight and bias
w= torch.rand(10, 1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

In [44]:
x = torch.rand(1,10)

In [45]:
x

tensor([[0.1383, 0.1146, 0.9847, 0.6809, 0.3268, 0.2453, 0.3029, 0.1616, 0.2645,
         0.2757]])

In [54]:
output = torch.matmul(x,w) + b

In [55]:
loss = 1 - output

In [58]:
print(loss)    #print(output)

tensor([[-0.5079]], grad_fn=<RsubBackward1>)


In [59]:
loss.backward()

In [62]:
print(w.grad) #b.grad

tensor([[-0.1383],
        [-0.1146],
        [-0.9847],
        [-0.6809],
        [-0.3268],
        [-0.2453],
        [-0.3029],
        [-0.1616],
        [-0.2645],
        [-0.2757]])


In [63]:
#update weight by clearing gradients
with torch.no_grad():
    w = w - 0.0001 * w.grad.data

In [64]:
w

tensor([[0.8005],
        [0.9223],
        [0.4350],
        [0.0023],
        [0.0800],
        [0.2783],
        [0.4407],
        [0.9435],
        [0.6017],
        [0.6926]])