In [1]:
import torch
import numpy as np

In [2]:
torch.cuda.is_available()

False

In [3]:
some_data = [[1,2], [3,4]]

In [4]:
some_data

[[1, 2], [3, 4]]

In [5]:
type(some_data)

list

In [6]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [7]:
some_data = torch.tensor(some_data) #convert to torch tensor

In [8]:
type(some_data)

torch.Tensor

In [9]:
some_data.dtype

torch.int64

In [10]:
numpy_array = np.random.rand(3,4)

In [11]:
numpy_array

array([[0.81830584, 0.49413431, 0.57886344, 0.17281597],
       [0.65563866, 0.38540136, 0.92625184, 0.49293307],
       [0.82979408, 0.04283592, 0.46204898, 0.79864833]])

In [12]:
torch.from_numpy(numpy_array)  #convert to torch tensor

tensor([[0.8183, 0.4941, 0.5789, 0.1728],
        [0.6556, 0.3854, 0.9263, 0.4929],
        [0.8298, 0.0428, 0.4620, 0.7986]], dtype=torch.float64)

In [13]:
torch.tensor(numpy_array) #convert to torch tensor

tensor([[0.8183, 0.4941, 0.5789, 0.1728],
        [0.6556, 0.3854, 0.9263, 0.4929],
        [0.8298, 0.0428, 0.4620, 0.7986]], dtype=torch.float64)

In [14]:
torch.zeros(2,3) #torch.ones(2,3) torch.rand(3,4)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
my_tensor = torch.rand(3,4)

In [16]:
my_tensor.dtype

torch.float32

In [17]:
my_tensor.device

device(type='cpu')

In [18]:
my_tensor

tensor([[0.1261, 0.7539, 0.2053, 0.4830],
        [0.8893, 0.1532, 0.3889, 0.9161],
        [0.7767, 0.4235, 0.5161, 0.7992]])

In [19]:
my_tensor[:, 1:3]  #slice 2nd and 3rd col

tensor([[0.7539, 0.2053],
        [0.1532, 0.3889],
        [0.4235, 0.5161]])

In [20]:
#elementwise mul
my_tensor.mul(my_tensor) #my_tensor*my_tensor

tensor([[0.0159, 0.5683, 0.0421, 0.2333],
        [0.7908, 0.0235, 0.1512, 0.8392],
        [0.6033, 0.1793, 0.2663, 0.6387]])

In [21]:
#matrix mul
my_tensor.matmul(my_tensor.T)  #torch.matmul(my_tensor, myy_tensor.T)
                               #my_tensor @ my_tensor.T

tensor([[0.8596, 0.7499, 0.9091],
        [0.7499, 1.8046, 1.6884],
        [0.9091, 1.6884, 1.6876]])

In [22]:
#sum elements of tensor
my_tensor.sum()     #my_tensor.sum(axis=0)-->rows  
                    #my_tensor.sum(axis=1)-->cols  

tensor(6.4311)

In [23]:
#torch. max, torch.min 

In [24]:
#concatenate
torch.cat([my_tensor, my_tensor], axis=1)
#torch.cat([my_tensor, my_tensor], axis=0)
#torch.cat([my_tensor, my_tensor], dim=1)

tensor([[0.1261, 0.7539, 0.2053, 0.4830, 0.1261, 0.7539, 0.2053, 0.4830],
        [0.8893, 0.1532, 0.3889, 0.9161, 0.8893, 0.1532, 0.3889, 0.9161],
        [0.7767, 0.4235, 0.5161, 0.7992, 0.7767, 0.4235, 0.5161, 0.7992]])

In [25]:
torch.nn.functional.softmax(my_tensor, dim=0)

tensor([[0.1976, 0.4411, 0.2804, 0.2555],
        [0.4238, 0.2419, 0.3369, 0.3940],
        [0.3787, 0.3170, 0.3826, 0.3505]])

In [26]:
my_tensor.shape  

torch.Size([3, 4])

In [27]:
my_tensor.size()  #my_tensor.size(0)-->rows
                  #my_tensor.size(1)-->cols

torch.Size([3, 4])

In [28]:
torch.rand(10, 8, 128, 128).size()  #(batchsize, channel, dim)

torch.Size([10, 8, 128, 128])

In [29]:
my_tensor

tensor([[0.1261, 0.7539, 0.2053, 0.4830],
        [0.8893, 0.1532, 0.3889, 0.9161],
        [0.7767, 0.4235, 0.5161, 0.7992]])

In [33]:
my_tensor.clip(0.2,0.8)

AttributeError: 'Tensor' object has no attribute 'clip'

In [32]:
#convert tensor to nparray
my_tensor.detach().numpy()

array([[0.12612253, 0.7538682 , 0.20529652, 0.48296845],
       [0.88925576, 0.15322459, 0.38885206, 0.91607213],
       [0.7767084 , 0.42348582, 0.5160869 , 0.7991755 ]], dtype=float32)